#!/bin/sh

APPS=/home/debian/apps
BIN_DIR=$APPS/blag
VENV_DIR=$BIN_DIR/venv

activate () {
	$VENV_DIR/bin/activate
}

cd $BIN_DIR
#source $VENV_DIR/bin/activate
activate
exec chpst -u debian $BIN_DIR/run.py
